apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: nolights
spec:
  selector:
    app: api
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: nolights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: api
          image: ghcr.io/redonti/no-lights-monitor/api:sha-d1686f23e3e3adccb8018352041506158a0a31c6
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: Europe/Kyiv
            - name: PORT
              value: "8080"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: nolights-db
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: nolights-secret
                  key: REDIS_URL
            - name: ADMIN_LOGIN
              valueFrom:
                secretKeyRef:
                  name: nolights-secret
                  key: ADMIN_LOGIN
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nolights-secret
                  key: ADMIN_PASSWORD
            - name: TELEGRAM_BOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nolights-secret
                  key: TELEGRAM_BOT_USERNAME
            - name: TELEGRAM_CHAT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nolights-secret
                  key: TELEGRAM_CHAT_USERNAME
            - name: OUTAGE_SERVICE_URL
              value: http://outage:8090
            - name: DTEK_SERVICE_URL
              value: http://dtek:3000
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
